system:
	sudo cp ./whatami-swaywm.service /etc/systemd/system/whatami-swaywm@.service
	sudo cp ./whatami-swaywm /usr/bin

user:
	sudo cp ./whatami-swaywm.service ~/.config/systemd/user/whatami-swaywm.service
	sudo cp ./whatami-swaywm /usr/bin
