#!/usr/bin/bash

set -euo pipefail
echo "Starting What Am I Exporter for Sway WM"

if [[ -z $SWAYSOCK ]]; then
        echo "SWAYSOCK is not set, sleeping then exit..."
        sleep 5
        exit 1
fi

DIR=$HOME/.data/swaywm/idle
FILE=$(/bin/date +%Y-%m-%dT%H:%M:%S)

echo "Saving to Path: $DIR/$FILE"

/bin/mkdir -p $DIR

/bin/swayidle -w \
    timeout 60 'echo "{\"type\": \"idle\", \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S)\"}"' \
    resume 'echo "{\"type\": \"resume\", \"timestamp\": \"$(date +%Y-%m-%dT%H:%M:%S)\"}"' >> $DIR/$FILE
