# coding: utf-8

"""
    What Am I

    .

    The version of the OpenAPI document: 0.1.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.i_usage_item_dto import IUsageItemDTO

class TestIUsageItemDTO(unittest.TestCase):
    """IUsageItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IUsageItemDTO:
        """Test IUsageItemDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IUsageItemDTO`
        """
        model = IUsageItemDTO()
        if include_optional:
            return IUsageItemDTO(
                name = 'Alacritty',
                start_time = 1751701000,
                end_time = 1751701520
            )
        else:
            return IUsageItemDTO(
        )
        """

    def testIUsageItemDTO(self):
        """Test IUsageItemDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
